--require("lazy").setup {
--    {
--        'lewis6991/impatient.nvim'
--    },
--    {
--        'norcalli/nvim-colorizer.lua'
--    },
--
--    {
--        'nvim-lua/plenary.nvim'
--    },
--
--    {
--        'nvim-lua/popup.nvim'
--    },
--
--    {
--        's1n7ax/nvim-terminal'
--    },
--
--    {
--        'nvim-tree/nvim-web-devicons'
--    },
--
--    {
--        'samjwill/nvim-unception',
--    },
--
--    {
--        'ahmedkhalf/project.nvim'
--    },
--
--    {
--        'kkoomen/vim-doge',
--        run = '<cmd>call doge#install()<cr>'
--    },
--
--    {
--        'nvim-lualine/lualine.nvim',
--    },
--
--    {
--        'L3MON4D3/LuaSnip',
--        run = 'make install_jsregexp'
--    },
--
--    {
--        'hrsh7th/nvim-cmp'
--    },
--
--    {
--        'hrsh7th/cmp-nvim-lsp'
--    },
--
--    {
--        'williamboman/mason.nvim',
--
--    },
--    { 'williamboman/mason-lspconfig.nvim' },
--    { 'neovim/nvim-lspconfig' },
--    { 'mhartington/formatter.nvim' },
--    {
--        'nvim-treesitter/nvim-treesitter',
--        build = ":TSUpdate"
--    },
--
--    {
--        'nvim-telescope/telescope.nvim',
--        tag = '0.1.0'
--    },
--
--    {
--        'nvim-telescope/telescope-fzf-native.nvim',
--        run = 'make'
--    },
--
--    {
--        'nvim-telescope/telescope-file-browser.nvim'
--    },
--
--    {
--        'sindrets/diffview.nvim'
--    },
--
--    { 'EdenEast/nightfox.nvim' },
--
--    {
--        'akinsho/bufferline.nvim',
--        version = "*",
--        dependencies = 'nvim-tree/nvim-web-devicons'
--    },
--    {
--        "catppuccin/nvim",
--        name = "catppuccin"
--    },
--
--    {
--        'numToStr/Comment.nvim'
--    }
--}
